receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlp_http/dynatrace:
    endpoint: ${env:DT_ENDPOINT}/api/v2/otlp
    headers:
      Authorization: "Api-Token ${env:DT_API_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug, otlp_http/dynatrace]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug, otlp_http/dynatrace]
